server:
  port: 8123  # ??
  servlet:
    context-path: /api   # ???????/api
    session:
      cookie:
        max-age: 259200
  # ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rating?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: rating
    password: 123456
  data:
    # Redis ??
    redis:
      database: 0
      host: 192.168.48.136
#      password: 123456
      timeout: 5000
      port: 6379

mybatis-plus:
  configuration:
    #????????
    map-underscore-to-camel-case: false
    # ???????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
  enable: true
  setting:
    language: zh_cn

# Pulsar配置
pulsar:
  service-url: pulsar://192.168.48.136:6650
  admin-url: http://192.168.48.136:8080
  tenant: public
  namespace: default
  topic: thumb-topic
